# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1= np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2= np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
a3= np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 2, 2), 3, dtype('int64'), 8, numpy.ndarray)

In [6]:
#create a random array size =(2,3,4,5)
random_array= np.random.randint(10,size=(2,3,4,5))
random_array

array([[[[8, 5, 3, 1, 1],
         [2, 4, 7, 4, 3],
         [9, 5, 2, 7, 3],
         [6, 8, 8, 6, 0]],

        [[6, 5, 7, 3, 5],
         [3, 1, 1, 9, 3],
         [0, 0, 7, 3, 9],
         [1, 1, 3, 6, 7]],

        [[0, 4, 6, 9, 1],
         [4, 7, 4, 9, 0],
         [1, 5, 5, 1, 3],
         [4, 3, 0, 2, 5]]],


       [[[3, 0, 1, 0, 8],
         [3, 2, 0, 4, 3],
         [4, 5, 3, 9, 9],
         [9, 8, 9, 6, 0]],

        [[7, 5, 5, 6, 3],
         [1, 3, 8, 4, 8],
         [7, 0, 3, 7, 4],
         [3, 1, 1, 3, 4]],

        [[9, 6, 4, 1, 0],
         [1, 8, 4, 3, 0],
         [7, 4, 6, 7, 0],
         [3, 4, 2, 0, 9]]]], dtype=int32)

In [7]:
# Get the first 2 rows of latest array you created
random_array[:1,:1,:2]

array([[[[8, 5, 3, 1, 1],
         [2, 4, 7, 4, 3]]]], dtype=int32)

In [8]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:1,:1,:2,:2]

array([[[[8, 5],
         [2, 4]]]], dtype=int32)

In [9]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array2= np.random.randint(10,size=(3,5))
ones_array= np.ones((3,5))
ones_array


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# Add the two arrays together
random_array2 + ones_array


array([[ 6.,  7.,  9.,  7.,  2.],
       [ 7.,  3.,  4., 10.,  1.],
       [10., 10., 10.,  6.,  4.]])

In [11]:
# Create another array of ones of shape (5, 3)
another_array = np.ones((5,3))
another_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# Try add the array of ones and the other most recent array together
ones_array + another_array

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [ ]:
# Create another array of ones of shape (3, 5)
another_array2 = np.ones((3,5))
another_array2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Subtract the new array of ones from the other most recent array
another_array2 - ones_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Multiply the ones array with the latest array
ones_array * another_array2

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [ ]:
# Take the latest array to the power of 2 using '**'
another_array2 ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Do the same thing with np.square()
np.square(another_array2)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Find the mean of the latest array using np.mean()
np.mean(another_array2)

np.float64(1.0)

In [ ]:
# Find the maximum of the latest array using np.max()
np.max(another_array2)

np.float64(1.0)

In [ ]:
# Find the minimum of the latest array using np.min()
np.min(another_array2)

np.float64(1.0)

In [ ]:
# Find the standard deviation of the latest array
np.std(another_array2)

np.float64(0.0)

In [ ]:
# Find the variance of the latest array
np.var(another_array2)

np.float64(0.0)

In [ ]:
# Reshape the latest array to (3, 5, 1)
another_array2.reshape((3,5,1))

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [ ]:
# Transpose the latest array
another_array2.T
another_array2.T.shape
another_array2.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

What does the transpose do?

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_1= np.random.randint(10,size=(3,3))
array_2= np.random.randint(10,size=(3,2))


In [ ]:
# Perform a dot product on the two newest arrays you created
np.dot(array_1, array_2)

array([[86, 63],
       [56, 32],
       [68, 46]], dtype=int32)

In [14]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
first_array= np.random.randint(10,size=(4,3))
second_array= np.random.randint(10,size=(4,3))

In [15]:
# Perform a dot product on the two newest arrays you created
np.dot(first_array, second_array)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [16]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

np.dot(first_array.T, second_array)


array([[ 87,  92, 107],
       [104, 112, 152],
       [ 97,  98, 111]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [23]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand1 = np.random.randint(10,size=(3,4))
rand2 = np.random.randint(10,size=(3,4))
rand1, rand2

(array([[0, 7, 7, 8],
        [8, 2, 1, 5],
        [8, 5, 9, 0]], dtype=int32),
 array([[6, 2, 1, 8],
        [2, 5, 6, 3],
        [4, 2, 6, 4]], dtype=int32))

In [24]:
# Compare the two arrays with '>'
rand1 > rand2

array([[False,  True,  True, False],
       [ True, False, False,  True],
       [ True,  True,  True, False]])

What happens when you compare the arrays with `>`?

In [25]:
# Compare the two arrays with '>='
rand1 >= rand2

array([[False,  True,  True,  True],
       [ True, False, False,  True],
       [ True,  True,  True, False]])

In [26]:
# Find which elements of the first array are greater than 7
rand1 > 7

array([[False, False, False,  True],
       [ True, False, False, False],
       [ True, False,  True, False]])

In [27]:
# Which parts of each array are equal? (try using '==')
rand1 == rand2

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [28]:
# Sort one of the arrays you just created in ascending order
rand1.sort()
rand1

array([[0, 7, 7, 8],
       [1, 2, 5, 8],
       [0, 5, 8, 9]], dtype=int32)

In [29]:
# Sort the indexes of one of the arrays you just created
rand1.argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [30]:
# Find the index with the maximum value in one of the arrays you've created
rand1.argmax()

np.int64(11)

In [31]:
# Find the index with the minimum value in one of the arrays you've created
rand1.argmin()

np.int64(0)

In [32]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
rand1.argmax(axis=1)

array([3, 3, 3])

In [33]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
rand1.argmin(axis=0)

array([0, 1, 1, 0])